### ISSUE TITLE
issue: click marker event callback

### ISSUE THREAD

**Issue by zzpmaster** [leftstick/angular2-baidu-map#1]
when click marker point，i can't get a event. will be open mark point click event?

**Comment by leftstick** [comment]
In currently implementation, when you provide `marker.title` and `marker.content`, i will simply display a infoWindow while clicking the `marker`, Nothing else.

My guess is, you want to catch this clicking event, and have some extra works there?

It's possible to give an event in this approach:

```html
<baidu-map ak="put your ak here" [options]="opts" (onMarkerClicked)="click($event)"></baidu-map>
```

```javascript
click(e) {
    console.log(e);//e here is the marker instance created via `BMap.Marker` class
}
```

Do u have any suggestion?

**Comment by zzpmaster** [comment]
Thank you for your answer to this question. i think most requirements need to change UI while clicking the `marker`,  so this popup ui can be customize.

if you add `onMarkerClicked` approach, i think this way is perfect.

**Comment by leftstick** [comment]
Which part you want to customize, The `BMap.InfoWindow`?

**Comment by zzpmaster** [comment]
No, not `BMap.InfoWindow`.  just need some extra work. 
 i'm so sorry i didn't make myself clear.

**Comment by leftstick** [comment]
That's fine, i think the new feature can be release today ^^

**Comment by leftstick** [comment]
You can try `2.2.0` now^^

**Comment by zzpmaster** [comment]
迅速にご対応頂き、ありがとうございます。
