### ISSUE TITLE
Any way to use customized InfoWindow?

### ISSUE THREAD

**Issue by shenfw1987** [leftstick/angular2-baidu-map#10]
I'm wondering if there is any way to use my Component as InfoWindow popup? Looks like Baidu's InfoWindow is set by innerHtml and Angular cannot detect the DOM change : (

**Comment by leftstick** [comment]
Unfortunately, it's not supported by `angular2-baidu-map` natively, and i am very sorry that i cannot help on this repo recently due to healthy issue.

Maybe you can listen on `onMarkerClicked` event, and create your own custom overlay?

**Comment by shenfw1987** [comment]
Yeah I'll look into that sometime.  Take care of yourself bro!
