### ISSUE TITLE
有计划更新到angular9吗

### ISSUE THREAD

**Issue by linguangyu** [leftstick/angular2-baidu-map#106]

**Comment by leftstick** [comment]
现在就支持，看例子：[angular9-baidu-map-example](https://github.com/leftstick/angular9-baidu-map-example)

**Comment by linguangyu** [comment]
> 现在就支持，看例子：[angular9-baidu-map-example](https://github.com/leftstick/angular9-baidu-map-example)

![image](https://user-images.githubusercontent.com/24983193/80185308-ba4e2800-863e-11ea-8509-4a6caf5f1e48.png)

![image](https://user-images.githubusercontent.com/24983193/80185341-c3d79000-863e-11ea-8ab3-d4bc72fa78ad.png)

你好， 请教下。  我安装了 版本8后。 引入一些东西路径是对的。 但是却报错。

**Comment by linguangyu** [comment]
我在你的列子里面也有这样的问题。。 

是我引入的这些取消了还是什么原因。 我在npm包里面是能找到 这些export出来的。

**Comment by leftstick** [comment]
从截图里看不出有助于解决问题的内容。请提供有效的可复现demo

**Comment by leftstick** [comment]
但有些东西需要改进

1. 请从 `angular2-baidu-map` 里导出你要的内容。不要直接引用`angular2-baidu-map/lib/` 下面的模块。
2. 按理说你不应该直接使用`MarkerComponent`，所以你引入他做什么？

**Comment by linguangyu** [comment]
> 但有些东西需要改进
> 
> 1. 请从`angular2-baidu-map`里开始你要的内容。不要直接引用`angular2-baidu-map/lib/`下面的模块。
> 2. 按理说你不应该直接使用`MarkerComponent`，所以你约会他做什么？

在你提供的例子里面 我在app.component.ts 里面添加了
![image](https://user-images.githubusercontent.com/24983193/80189580-790d4680-8645-11ea-8921-5c63c151dfb2.png)

就会报错。 你看下

[angular9-baidu-map-example-master.zip](https://github.com/leftstick/angular2-baidu-map/files/4527531/angular9-baidu-map-example-master.zip)
这是demo

**Comment by linguangyu** [comment]
我是从版本4.3.2 更新到了9

**Comment by leftstick** [comment]
![Screen Shot 2020-04-24 at 17 39 42](https://user-images.githubusercontent.com/1059956/80198544-c93ed580-8652-11ea-9327-c594beeba04a.png)


你引入的这个`angular2-baidu-map/lib/helpers/transformer`，根本就不是`.ts`，而是类型声明文件`.d.ts`，里面只有声明没有实现，当然会报错。。。


这个，使用最好还是按照文档从 `angular2-baidu-map`直接引入。


如果你需要哪个东西是我没导出的，可以再开issue来问。至于`helper/`下的内容，本来就是内部使用的，你不应该用。非要用的话，自己拷贝一份好了。那些函数随时可能以为升级做修改。我不会把他们暴露出去的
