### ISSUE TITLE
self.context.setStyles is not a function

### ISSUE THREAD

**Issue by rickdgit** [leftstick/angular2-baidu-map#11]
Hey 
I use this library as same as the 'usage'  selection on [this page](https://leftstick.github.io/angular2-baidu-map/).

However, i met an error.

Error msg shows that 

 >EXCEPTION: self.context.setStyles is not a function
>TypeError: self.context.setStyles is not a function
>    at _View_BaiduMapComponent0.detectChangesInternal (BaiduMapComponent.ngfactory.js:62)

![screen shot 2016-11-04 at 15 32 50](https://cloud.githubusercontent.com/assets/4945599/20021485/fd0e1e3e-a2a3-11e6-8e3c-9b9a6fb0d2b0.png)

When i was trying to run ur demo, i met a error when i run npm install 
>ERROR in ./src/index.ts
>(1,126): error TS2307: Cannot find module '@angular/core'.

<img width="930" alt="screen shot 2016-11-04 at 15 34 36" src="https://cloud.githubusercontent.com/assets/4945599/20021546/3f55f94c-a2a4-11e6-9890-027877d13f11.png">

I run demo by 
>npm install 
>npm start  

Thanks for any suggestions

**Comment by rickdgit** [comment]
I install the package manually. It works.
There are several error msg in console.

>error TS2304: Cannot find name 'Map'.
>error TS2304: Cannot find name 'Set'.
>error TS2304: Cannot find name 'Promise'.

Besides, I can't use the most up tp data libraries for baidu-map. Wondering can u update it ?

**Comment by leftstick** [comment]
My demo requires `peerDependencies` which will not be installed automatically, they are:

```javascript
"peerDependencies": {
    "@angular/common": "~2.0.1",
    "@angular/core": "~2.0.1",
    "rxjs": "~5.0.0-beta.12",
    "zone.js": "^0.6.25"
},
```

And for the error in console, like `Cannot find name 'Map'`, this caused you have missed the `typings`, try run `npm run typings`. Then, `npm start` for the demo anain

**Comment by rickdgit** [comment]
Gotcha Thanks for ur explanation.
Besides, wondering could u update the requirement libraries to the most up to date versions.
For example, @angular2/core from 2.0.1 0 -> 2.1.0

**Comment by leftstick** [comment]
@rickdgit  `2.5.1` upgrades all the dependencies to latest version
