### ISSUE TITLE
Angular 9 compatibility

### ISSUE THREAD

**Issue by b-legrand** [leftstick/angular2-baidu-map#111]
I'm trying to upgrade a project that uses this library to angular 9 and ivy 

The library still works like a charm, but npm warns about missing peer dependencies.

```
npm WARN angular2-baidu-map@8.0.0 requires a peer of @angular/common@^8.2.13 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-baidu-map@8.0.0 requires a peer of @angular/core@^8.2.13 but none is installed. You must install peer dependencies yourself.
```

Are there any plans on your part to support angular 9, and if no, would you be interested in an upgrade pull-request ?

**Comment by leftstick** [comment]
@b-legrand

`angular2-baidu-map` should work with angular 9 and ivy. 

The only thing we need to do is remove missing peerDependencies warning.

pr is welcome, thanks
