### ISSUE TITLE
在ionic2中使用的问题(2016/11/10下载的版本)

### ISSUE THREAD

**Issue by csdcsd** [leftstick/angular2-baidu-map#12]
您好！
下载了项目的最新版本，照demo的引用方式不成功，遂直接引用源码：'../../../node_modules/angular2-baidu-map/src/index'(在项目中的绝对路径)，但是程序只执行了ngOnInit，地图实例没有创建出来，也更没有触发onMapLoaded()，不知道是什么问题

**Comment by leftstick** [comment]
@csdcsd 你的地图`ak`值确认是正确可用的么？

理论上，`ngOnInit`执行了，就表示`src/Loader.ts`一定会被调用，我能想到的可能性就是地图脚本加载失败了

**Comment by csdcsd** [comment]
ak确认可用，项目其他地方也在用到同一个ak的，那么地图脚本加载失败可以有什么解决方案吗？

**Comment by csdcsd** [comment]
是部署在本地的测试环境，引用源码的情况下，跑完OnInit就没有任何反应了，地图界面也没用出来，
然后这是按照demo中引用`'angular2-baidu-map'`的方式，编译时报的错：
![image](https://cloud.githubusercontent.com/assets/23096246/20261253/f9359386-aa97-11e6-801b-e8fc49495024.png)

**Comment by leftstick** [comment]
首先，你用`rollup`就最好还是引用源码吧，我没用过`rollup`，但猜测可能和他的静态模块要求有关。

其次，本地测试，打开`dev tools`的`network`，filter一下这个请求`api.map.baidu.com/api?v=2.0`，我想知道发这个请求是用的协议是什么，以及返回的状态，内容都是什么

**Comment by csdcsd** [comment]
这个吗？
```
**General**
Request URL:http://api.map.baidu.com/api?v=2.0
Request Method:GET
Status Code:200 OK
Remote Address:112.80.255.107:80
**Response Header**
Content-Length:206
Content-Type:text/javascript;charset=utf-8
Date:Tue, 15 Nov 2016 01:42:02 GMT
Http_x_bd_logid:3045418841
Http_x_bd_logid64:11218418652763450188
Http_x_bd_product:map
Http_x_bd_subsys:apimap
Server:apache
Vary:Accept-Encoding
**Request Headers**
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:BAIDUID=95F48E0CF4A30D95A25DEF1F3CE91BA1:FG=1; BIDUPSID=95F48E0CF4A30D95A25DEF1F3CE91BA1; PSTM=1467512058; PRY=1; BDUSS=1RYQTRhcXRmWGs0bGFjYTh4b1dwSENLQzJ4dG5mSTlqWHFFMmlzZ2hPekF5d3BZQUFBQUFBJCQAAAAAAAAAAAEAAAAZfc0htqu3519fuvrBywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA-41fAPuNXd; Hm_lvt_5650c092812f8659cdfe23eeb42024ef=1474972647; Hm_lvt_21b27145da0487d1e9f52a8e5576e564=1474857488,1474875440,1474881694,1475030490; MCITY=-179%3A; pgv_pvi=3533030400; PSINO=5; H_PS_PSSID=1421_19036_21091_17001_21264_21455_21409_21378_21525_21190_21307
Host:api.map.baidu.com
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
**Query String Parameters**
v:2.0
```

**Comment by leftstick** [comment]
@csdcsd 看请求的确是成功了，那我想只有你有环境，只能麻烦你自己调试一下，[Loader.ts - 21 ~ 26](https://github.com/leftstick/angular2-baidu-map/blob/master/src/Loader.ts#L21-L26)，加几个`console`/`alert`看下`baidumapinit`方法是否执行了

**Comment by csdcsd** [comment]
@leftstick 谢谢了，但是调试过后，发现他连`index`的`constructor`和`ngOnInit`都没有进，`Loader.ts`当然也没进  ( ⊙ _ ⊙ )

**Comment by leftstick** [comment]
那这个问题就诡异了，如果压根没进去，那地图脚本的那个请求是谁发的？

**Comment by csdcsd** [comment]
@leftstick 那是我误解了，那个请求是我手动发的，程序中没有发出这个请求=_=

**Comment by leftstick** [comment]
如果连`src/index.ts`的`ngOnInit`都没有进入的话，又没报错，我只能猜测是调用的地方有问题了。你再贴贴你是怎么使用的吧

**Comment by csdcsd** [comment]
那麻烦你给看看了
这是引用：`import {BaiduMap, OfflineOptions, ControlAnchor, NavigationControlType} from '../../../node_modules/angular2-baidu-map/src/index';`；

这是具体使用，跟demo中的一样：
`@Component({
	templateUrl : 'hotel-map.html' //同级目录下的文件
})
export class HotelMapPage implements OnInit {
	hLng : number;
	hLat : number;
	hotelName : string;
	address : string;
	opts : any;
	offlineOpts : OfflineOptions;

	constructor (
		public navCtrl : NavController,
		public navParams : NavParams
	) {
		let params = navParams.data;
		this.hLng = params.hotel.lng;
		this.hLat = params.hotel.lat;
		this.hotelName = params.hotel.name;
		this.address = params.hotel.address;
	}
	
	ngOnInit() {
		this.opts = {
            center: {
                longitude: this.hLng,
                latitude: this.hLat
            },
            zoom: 17,
            markers: [{
                longitude: this.hLng,
                latitude: this.hLat,
                title: this.hotelName,
                content: this.address,
                autoDisplayInfoWindow: true
            }],
            geolocationCtrl: {
                anchor: ControlAnchor.BMAP_ANCHOR_BOTTOM_RIGHT
            },
            scaleCtrl: {
                anchor: ControlAnchor.BMAP_ANCHOR_BOTTOM_LEFT
            },
            overviewCtrl: {
                isOpen: false
            },
            navCtrl: {
                type: NavigationControlType.BMAP_NAVIGATION_CONTROL_LARGE
            }
        };

        this.offlineOpts = {
            retryInterval: 5000,
            txt: 'NO-NETWORK'
        };
	}
	
	loadMap(e : any) : void {
        console.log(JSON.stringify(e));//e here is the instance of BMap.Map
    }

    clickMarker(marker : any) : void {
        console.log('The clicked marker is', marker);
    }
}`；
传的值都是验证过有效的，`ngOnInit`也跑完了

**Comment by leftstick** [comment]
两个问题：

1. 我没看到你的`@component`里定义`selector`属性，这么写可以么？
2. 你调用`HotelMapPage`的代码什么样子，我指那个`@NgModule`的那块

**Comment by csdcsd** [comment]
`selector`属性，在`ionic2`中倒是没什么影响，下面是`@NgModule`的代码：
```
@NgModule({

    declarations : [
        ChangyiHotelBookingApp, AboutUsPage, BillingDetailPage,	CardHotelPage,ChooseCityPage,
		ChooseDatePage,ChooseTravelersPage,CommonListPage,CompleteInfoPage,FillcOrderPage,
		FillOrderPage,FindCustomerPage,HotelDescPage,HotelDetailPage,HotelListPage,HotelMapPage,
		HotelSearchPage,InvoiceInfoPage,LoginBindPage,MyOrderPage,MySetPage,OrderDetailPage,
		OrderListPage,SearchResultPage,TabsPage,TravelersListPage,TripCardPage,TripListPage,
		UserCenterPage,WXPayPage
    ],

    imports : [
        IonicModule.forRoot(ChangyiHotelBookingApp)
    ],
entryComponents中。
    bootstrap: [IonicApp],

    entryComponents: [
        ChangyiHotelBookingApp, AboutUsPage, BillingDetailPage,	CardHotelPage,ChooseCityPage,
		ChooseDatePage,ChooseTravelersPage,CommonListPage,CompleteInfoPage,FillcOrderPage,
		FillOrderPage,FindCustomerPage,HotelDescPage,HotelDetailPage,HotelListPage,HotelMapPage,
		HotelSearchPage,InvoiceInfoPage,LoginBindPage,MyOrderPage,MySetPage,OrderDetailPage,
		OrderListPage,SearchResultPage,TabsPage,TravelersListPage,TripCardPage,TripListPage,
		UserCenterPage,WXPayPage
    ],

    providers: [
        BaiduAPI,  WeixinAPI, UrlManage, HotelService, LocationService, MemberService,
        OrderService, TimeUtils, Storage, AlertUtils
    ],

	schemas : [CUSTOM_ELEMENTS_SCHEMA]
})
```

**Comment by leftstick** [comment]
`declarations`里没有`BaiduMap`，这个你需要引入的，否则`ng2`不会认识那个`baidu-map`的标签，如果你看我的demo代码:[main.ts - 13](https://github.com/leftstick/angular2-baidu-map/blob/master/demo/js/main.ts#L13)

**Comment by csdcsd** [comment]
对了这个给忘了！之前一直没引用成功所以给去掉了，多谢提醒；现在地图实例出来了，但是只有一小块，一拖动就没了，还报了个错：
```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at HotelMapPage.loadMap (NavigationControlType.ts:1)
    at _View_HotelMapPage0._handle_onMapLoaded_11_0 (HotelMapPage.ngfactory.js:231)
    at view.js:403
    at SafeSubscriber.schedulerFn [as _next] (async.js:94)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:223)
    at SafeSubscriber.next (Subscriber.js:172)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at EventEmitter.Subject.next (Subject.js:55)
    at EventEmitter.emit (async.js:74)
```

![image](https://cloud.githubusercontent.com/assets/23096246/20337113/df492668-ac09-11e6-82fd-f6f7c766ea60.png)

**Comment by leftstick** [comment]
我猜是你的这句话引起的：

```javascript
console.log(JSON.stringify(e));//e here is the instance of BMap.Map
```

如果要看`map`实例，直接`console.log(e)`好了
