### ISSUE TITLE
如何去掉左下角的百度logo哟

### ISSUE THREAD

**Issue by hefujie1988** [leftstick/angular2-baidu-map#126]
![image](https://user-images.githubusercontent.com/26532399/119318231-9e86dc80-bcab-11eb-8844-f30db731cc4e.png)

**Comment by leftstick** [comment]
没见过官方手段，自己加hack 代码，隐藏那个block 就好了
![Screen Shot 2021-05-24 at 17 26 36](https://user-images.githubusercontent.com/1059956/119327163-4228ba80-bcb5-11eb-9154-90bf204737c1.png)
