### ISSUE TITLE
Error when compiling with angular-cli

### ISSUE THREAD

**Issue by subarroca** [leftstick/angular2-baidu-map#16]
I'm getting this error when trying to build for prod:
`ERROR in Unexpected value 'BaiduMap'`

I've got 6 or 7 plugins and this one seems to be the only one failing and also it's the only one that's not bundled in a module.

Has this happened to you? Could you move your project to a module structure?

Thanks!

**Comment by leftstick** [comment]
For the error, can you show me how you use it? Cause i never got that error before.


For module structure, i am trying to move it into `next` version, but cannot make sure when it can be finished, since `baidu-map` itself implemented in very hack way, hard to get it integrated with `Zone.js`. I believe it is a blocker issue for me right now. But in case you are interesting in it, please check `next` branch, and give me PR for solving errors

**Comment by subarroca** [comment]
I think the problem is latest versions of angular-cli try to build in aot mode and somehow that fails. I've been using it as stated in your readme and when moving from beta 25 to beta 30 started crashing.
I'll try to check it and I'll see if I can modularize your repo. Thanks!

**Comment by bobvandevijver** [comment]
I believe I have the same error, did you find anything to solve this? I'm using this in Ionic 2 by the way.

**Comment by leftstick** [comment]
I am not familiar with ionic, and lack of time for maintaining this repo(it was not well designed at the very begining. My bad).

Suggest you use baidu-SDK directly. Sorry for the inconvenient usage

**Comment by FreezeSoul** [comment]
咳，遇到了同样的问题，还是自己直接封装吧

**Comment by subarroca** [comment]
I've got a version with module and some AoT possible problems fixed but I'm still getting:

```
ERROR in Unexpected value 'BaiduMapModule in .../node_modules/angular2-baidu-map/dist/baidu-map.module.d.ts' declared by the module 'Ma
pModule in .../src/app/shared/map/map.module.ts'. Please add a @Pipe/@Directive/@Component annotation.
```

I know you don't currently have a module but I stated above

**Comment by wcnvidia** [comment]
I have a same issue in angular version4.0.

**Comment by abcfy2** [comment]
+1 for angular 4.0 has the same issue.

**Comment by leftstick** [comment]
refactor with module structure in `3.0.0`, @subarroca you can verify in your env if you like?

@abcfy2 @wcnvidia  i am thinking to give up this repo, it's better you use baidu-SDK directly, or create your own module

**Comment by subarroca** [comment]
Thanks for your efforts.

I'm currently getting 
```
ERROR in Unexpected value 'BaiduMapModule in .../node_modules/angular2-baidu-map/dist/index.d.ts' imported by the module 'MapModule
 in .../src/app/shared/map/map.module.ts'. Please add a @NgModule annotation.
```

**Comment by leftstick** [comment]
@subarroca , have you tried with source code directly? like:

```typescript
import { BaiduMapModule } from 'angular2-baidu-map/src';
```

**Comment by subarroca** [comment]
Yes, the problem might have something related with metadata maybe? Chek out this video: https://www.youtube.com/watch?v=unICbsPGFIA

**Comment by leftstick** [comment]
Make sense, maybe caused by `webpack` which i used for dist build. I created a new version(`3.0.1`) with `ngc` as dist build compiler, @subarroca would you like to try if it works?

**Comment by subarroca** [comment]
It looks fine now. I'll do more checkings tomorrow and I'll let you know.

thanks a lot!

**Comment by subarroca** [comment]
I've tried it and it compiles great :1st_place_medal:
