### ISSUE TITLE
how to dragging the maker?

### ISSUE THREAD

**Issue by ZeyZhang** [leftstick/angular2-baidu-map#17]
i want to dragging the marker,and get this  maker's point. how to do?

**Comment by leftstick** [comment]
I can simply add `draggable` support for you. But since i have issue with upgrade this lib into `modular` pattern. I strongly recommend you implement map functions yourself and get rid of this lib until i find way solve my issue.

Do you still need `draggable` support?

**Comment by ZeyZhang** [comment]
yes，Can you express it in Chinese？

**Comment by leftstick** [comment]
好呀，是这样的。我可以在现在的版本上给你立刻加一个拖拽支持。但因为现在版本最初的设计缺陷，将来也不太可能会有更好的扩展性。也就是说，将来你肯定还会遇到各种想要支持的功能，然而现在的版本就做不到了。

于是我想要升级，你可以看看`next`分支，已经在做了。可惜的是遇到了一个问题，百度地图的sdk似乎对`click`事件有自己的封装，这和`zone.js`集成时就完全不工作了。于是我的新版本几乎做不出来了，除非我能想到办法搞清楚百度地图的sdk到底为什么喝`zone.js`有冲突。然而由于各种原因，近期都没时间研究这个项目，于是搁置了。

所以我的建议是，放弃使用这个库，自己直接调用百度地图sdk好了。

当然如果你坚持，我的确可以在现在版本上家一个拖拽支持，但潜在风险你也要知道，因为设计缺陷，将来遇到其他问题的可能性会非常大

**Comment by ZeyZhang** [comment]
地图只是小功能，后续基本不会增加其他功能，只需要拖拽，然后获得拖拽之后maker的坐标就可以了

**Comment by leftstick** [comment]
OK, 那我加好了。你可以在[readme](https://github.com/leftstick/angular2-baidu-map/blob/master/README.md) 里找到用法了。

为marker新增了一个属性`enableDragging`，使得它可以拖拽，然后你可以在`(onMarkerClicked)="clickMarker($event)"`里，获取marker当前的位置`console.log('The clicked marker is', marker.getPosition());`

**Comment by ZeyZhang** [comment]
能否在拖拽结束就获得maker坐标

**Comment by leftstick** [comment]
这就是我说的设计缺陷了，我在源码里当然可以获取，但通过什么方式给你呢？这是我想放弃当前版本的主要原因

**Comment by ZeyZhang** [comment]
好的，多谢
