### ISSUE TITLE
center定位不准

### ISSUE THREAD

**Issue by ZeyZhang** [leftstick/angular2-baidu-map#19]
center定位偏差很大，请问是什么原因

**Comment by leftstick** [comment]
可以先用官网的[例子](http://lbsyun.baidu.com/jsdemo.htm#a1_2)试一下你的经纬度，看看用官方demo定位是否准确先

**Comment by ZeyZhang** [comment]
我试了一下，官方的是准的，我弄错了，不是定位不准，是maker的位置不准。我定位的坐标和maker的坐标是一样的，但是两者有偏差

**Comment by ZeyZhang** [comment]
`  ngOnInit() {
    this.opts = {
      center: {
        longitude: 120.506191,
        latitude: 30.245554
      },
      zoom: 15,
      markers: [{
        longitude: 120.506191,
        latitude: 30.245554,
        title: '测试',
        content: '测试内容...',
        enableDragging:true
      }],
      scaleCtrl: {
        anchor: ControlAnchor.BMAP_ANCHOR_BOTTOM_LEFT
      },
    };`

`<baidu-map ak="hwSgLNwZSEj44eGiu5bqYdHMnDLOkbgo"
	    	      (onMarkerClicked)="clickMarker($event)"
	    	      [options]="opts"
	    	      [offline]="offlineOpts"
                      (onMapLoaded)="loadMap($event)"
	    	      (onMarkerClicked)="clickMarker($event)">
</baidu-map>`

**Comment by leftstick** [comment]
定位有偏差的意思是？能否举例说明

**Comment by ZeyZhang** [comment]
就是maker位置，和定位的位置是不一样的，定位的位置大概在maker的偏右边很多的地方。我是用在ng2-admin里面的modal框里，会不会是css影响到了；

图片复制过来失败了，没办法展示

**Comment by leftstick** [comment]
如果是默认的marker，不应该偏移，的确有可能被其他css样式影响，或许你`inspect element`看一下，`marker`的html结构大致如下：

```html
<span class="BMap_Marker BMap_noprint" unselectable="on" "="" style="position: absolute; padding: 0px; margin: 0px; border: 0px; cursor: pointer; background: url(&quot;http://api0.map.bdimg.com/images/blank.gif&quot;); width: 19px; height: 25px; left: 240px; top: 175px; z-index: -6049110;" title=""></span>
```

你可以看下，上面是否有属性被其他css覆盖了。

**Comment by ZeyZhang** [comment]
maker的没有被覆盖只是top和left和你的不一样，我的maker坐标放在官方例子上面和我的是一样的位置，只是定位是不准确的，我不知道造成的原因是什么？

**Comment by leftstick** [comment]
`left`, `top`默认都是百度sdk计算的，我并没有给`marker`设置`offset`。能否把你`inspect element`的结果截图来看看，像我这种：

<img width="1086" alt="screen shot 2017-03-22 at 6 14 38 pm" src="https://cloud.githubusercontent.com/assets/1059956/24193143/33108f9a-0f2c-11e7-8bcc-6638a694ca19.png">

**Comment by ZeyZhang** [comment]
我图片传不上去，直接发你GitHub上留的邮箱了

**Comment by leftstick** [comment]
我本地测试下来确实没有这个问题，或许你可以尝试把地图从modal里移出来，放到普通页面里试试？

**Comment by ZeyZhang** [comment]
我试了一下，确实是modal影响了。可能是bootstrap的定位对地图产生了影响，谢谢了

**Comment by leftstick** [comment]
good to know. 解决问题的思路、策略往往比解决的方法更重要，恭喜你
