### ISSUE TITLE
Use in Newest Angular2

### ISSUE THREAD

**Issue by xiabin1235910** [leftstick/angular2-baidu-map#2]
According to the newest Angular2, it comes out a new js file called 'systemjs.config.js'.

If we want to use the baidu map directly, we should add some codes in 'system.config.js' file as follow.

    var map = {
        'angular2-baidu-map':         'node_modules/angular2-baidu-map'
    };

    var packages = {
        'angular2-baidu-map':         { main: 'dist/angular2-baidu-map', defaultExtension: 'js'}
    };

Another issue is that the 'tsd install' is deprecated. Should use 'typings'.

So maybe need to update the readme.md file

**Comment by leftstick** [comment]
As i know, [system.js](https://github.com/systemjs/systemjs) is not mandatory. 

What you mean about the first issue, update README.md? or there is coding issue?

And the second issue, would you like to provide a PR for this updates?

**Comment by xiabin1235910** [comment]
In my opinion, it is no problem to be as an independent npm module.

But if we use it in angular2, I think we must register this module in the system.config.js.

Just like how the '@angular' module registers in this file. That's why we cannot find any script tag of '@angular' in index.html. 

Please refer to the, [](https://angular.io/docs/ts/latest/quickstart.html)   -->  systemjs.config.js

So it is not a coding issue. Just updating the readme.md file is OK.

**Comment by xiabin1235910** [comment]
According to the second issue, there is no PR for this update.

In package.json, I find that `"preinstall": "tsd install",`.

Because the tsd is deprecated, I recommend that use 'typings' instead.
Please refer to the [https://github.com/DefinitelyTyped/tsd](url)

And do you have any plan to implement the angular2 module of BaiduMap Lib?

**Comment by leftstick** [comment]
Now i think i got ur point. You mean it's better to add more description about how user can use this component in their project(especially for [System.js](https://github.com/systemjs/systemjs) user)?

It's fine to update the docs if i get time. But one thing should be mentioned here:

"But if we use it in angular2, I think we must register this module in the system.config.js."

Actually it's not true, if you look at the `quick start`, you would find following:

```
SystemJS happens to be a good choice. But we want to be clear that it was a choice and not a preference.
```

The reason why i haven't mention anything about [System.js](https://github.com/systemjs/systemjs) is, user can choose any technology they preferred to make the component works with `angular2`.

1. You can load it dynamically via [System.js](https://github.com/systemjs/systemjs) of course
2. It's also works well via [webpack](http://webpack.github.io/) during compiling phase, just like what i did at [gh-pages-demo](https://github.com/leftstick/angular2-baidu-map/tree/gh-pages)


The `tsd` part, will be updated later

And what you mean about "angular2 module of BaiduMap Lib"? The whole implementation of all BaiduMap functionalities? No such plan yet^^

Thanks for all your suggestion

**Comment by xiabin1235910** [comment]
OK. Thank you for your answer.
