### ISSUE TITLE
cannot set markers icon

### ISSUE THREAD

**Issue by lixujia** [leftstick/angular2-baidu-map#20]
Cannot set icons for marker, so I checked the code, and found in CoreOperations.ts:
``` javascript
    if (marker.icon) {
        var icon = new BMap.Icon(marker.icon, new BMap.Size(marker.width, marker.height));
        opts[icon] = icon;
    }
```
I thought opts[icon] = icon was wrong code.

**Comment by leftstick** [comment]
Yes, i believe you are correct. It's a typo. Fixed in `2.5.4`
