### ISSUE TITLE
请问什么时候增加点集合（MarkerClusterer）的功能？

### ISSUE THREAD

**Issue by alexspring123** [leftstick/angular2-baidu-map#22]

**Comment by leftstick** [comment]
这个项目由于一开始设计的不认真(惭愧)，使得到目前为止有些扩展不能。我打算弃坑有段时间了(健康和时间安排原因），只是碍于仍有不少朋友还在使用，所以继续维护一段时间。

对于任何比较高级的使用需求，还是建议直接使用baidu-SDK，或者创建你自己的模块吧。

**Comment by alexspring123** [comment]
很好的一个项目，可惜了；
