### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by legendlzh** [leftstick/angular2-baidu-map#28]
我想修改marker的icon。首先icon本身是string类型，然后我怎么给它复制都显示不出来，而且赋值后默认的标注图标也会消失。             
how to modify the icon?
when i give the icon a value,  the icon of baidumap is disappeared.
markers: [{
        longitude: 114.207911,
        latitude: 30.653114,
        title: 'AAAA',
        content: 'BBBB',
        icon: 'http://via.placeholder.com/50x50',
        autoDisplayInfoWindow: true,
        enableDragging: true,
      },
    ],

**Comment by leftstick** [comment]
设置marker的icon时，同时也需要`width`和`height`。

如果设置了`width`和`height`之后还是显示不出来，说明你的图片本身要比你设置的`width`和`height`大。最快的方法就是裁剪你的图片到你指定的大小
