### ISSUE TITLE
protocol

### ISSUE THREAD

**Issue by oceankai** [leftstick/angular2-baidu-map#31]
你好，在ionic2项目中，运行在手机上时，百度地图的URL是：“file://api.baidu.com......”并不是“https://api.baidu.com”，导致无法加载地图。在3.0版本中，还是可以<baidu-map [protocol]="https"></baidu-map>设置，但是现在版本无法设置了，请问要如何解决，谢谢

**Comment by leftstick** [comment]
等我更新一把啊，感谢发现问题。电脑今天升级升坏了，紧张修复中。。。。
