### ISSUE TITLE
Marker支持autoDisplayInfoWindow吗？

### ISSUE THREAD

**Issue by F5F5** [leftstick/angular2-baidu-map#33]
之前的版本有，，

最新版
    "angular2-baidu-map": "^4.0.1"
文档里没这个选项

**Comment by leftstick** [comment]
的确没有了。如你所见，`4.0.1`和之前的版本差异非常大。
之前的版本，仅提供简单的选项(大多数是开关性质)，并附带一系列默认的行为，其中就包含了默认打开`InfoWindow`。

现在的版本提供了更多的可能性，以及对百度地图sdk本身的穿透性，我不希望在这个库做太多对百度地图sdk的“特殊”封装，那样会增加本来已经熟悉百度地图sdk开发的同学的学习成本和使用成本。而且极大的影响了组件的扩展性。

如你文档里[marker](http://leftstick.github.io/angular2-baidu-map/#/apidoc/marker)所见，对于`InfoWindow`，现在需要你自己来控制。

只是当地图显示时自动显示`InfoWindow`目前还无法完成，我在考虑是否为`marker`组件也提供一个`loaded`事件，这样的话，开发者可以自己在`loaded`事件响应里写自己需要的任何行为，当然也可以显示一个`InfoWindow`

**Comment by F5F5** [comment]
明白了，谢谢，希望可以添加```loaded```事件

**Comment by leftstick** [comment]
`4.1.0`已到来，试试看
