### ISSUE TITLE
你好，路由切换之后getOverlays返回空数组

### ISSUE THREAD

**Issue by F5F5** [leftstick/angular2-baidu-map#34]
```
loadMap(map: any) {
    console.log('loaded');
    console.log(this.map);
    this.map = map;
    const BMap: any = window['BMap'];
    const marker = this.map.getOverlays()[0];
    const label = new BMap.Label('<div class="newPointLabel"><h1>此位置不对吗？</h1><p>快来拖动此图标到达正确位置</p></div>', {
      offset: new BMap.Size(-90, -116),
      enableMassClear: false
    });
    label.setStyle({
      backgroundColor: 'none',
      border: 0
    });
    marker.setLabel(label);
}
```

新手，请大牛见谅~

路由切换之后```map.getOverlays()```返回空数组导致无法获取```maker```，刷新则无问题，

我把这些写在```loadMap```里面可以吗？

请问一下可能是什么原因呢？

**Comment by leftstick** [comment]
因为`marker`是在创建完`map`之后才创建的，所以的确有这个可能性在`loadMap`回调里使用`this.map.getOverlays()`拿到的是空数组。至于你说页面刷新一下就没事了，我还真想不出来为什么。

不过看你的代码，应该是需要给`marker`上加一个`label`，那么我觉得和 #33 有相同的诉求，我会在下一个版本里为`marker`也加一个`loaded`事件，这样你用这个事件，就可以保证拿到你要的`marker`实例了。

需求敦促我加把劲，我尽快把这个功能做了并上线

**Comment by leftstick** [comment]
试试`4.1.0`吧，我给`marker`增加了`loaded`事件，你的操作写在那个里面
