### ISSUE TITLE
发现一个诡异的Bug

### ISSUE THREAD

**Issue by F5F5** [leftstick/angular2-baidu-map#36]
### 初始位置
![image](https://user-images.githubusercontent.com/15978277/33161652-d5c4e480-d05f-11e7-8b91-a48e53ae282d.png)
### 切换到一个有滚动条的路由下
![image](https://user-images.githubusercontent.com/15978277/33161674-fb548156-d05f-11e7-9145-55ff23f5fdc3.png)
### 再切回去
![1511421917 1](https://user-images.githubusercontent.com/15978277/33162108-abf5a5ba-d062-11e7-9fcc-a47a82ef59f4.jpg)

### 点的坐标就跑偏了。。。
是因为js比css快么?地图宽高我是通过
```
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
```
来设置的，

我发现修改```angular2-baidu-map\dist\src\components\map.component.js```
```
ngOnInit() {
        validate_1.nullCheck(this.options, 'options is required for <baidu-map>');
        validate_1.nullCheck(this.options.centerAndZoom, 'options.centerAndZoom is required for <baidu-map>');
        this._service
            .createMap(this.mapInstance.nativeElement, this.options)
            .then(map => {
            this.loaded.emit(map);
            return map;
        })
            .then(map => {
            this.addListener(map);
        });
    }
```
这里面```createMap```改成异步可以解决这个问题。

**Comment by leftstick** [comment]
`createMap`改成异步是什么意思？

**Comment by F5F5** [comment]
@leftstick ```setTimeout(()=>{},0)```

**Comment by leftstick** [comment]
@F5F5 哪里加你这段话？

**Comment by F5F5** [comment]
```
ngOnInit() {
        validate_1.nullCheck(this.options, 'options is required for <baidu-map>');
        validate_1.nullCheck(this.options.centerAndZoom, 'options.centerAndZoom is required for <baidu-map>');
        setTimeout(()=>{
            this._service
            .createMap(this.mapInstance.nativeElement, this.options)
            .then(map => {
            this.loaded.emit(map);
                return map;
            })
            .then(map => {
                this.addListener(map);
            });
        },0)
    }
```
但是好像有时候会报错``export is not defined```

**Comment by F5F5** [comment]
我中间那块是flex1，没有加载其他css，是不是切换的时候高度还没计算好导致map取到了之前的高度？

**Comment by leftstick** [comment]
你的宽高是js动态设置的么？

**Comment by F5F5** [comment]
不是，右边分三块header,content,footer
header和footer高度固定了，content是flex：1
map就在content里面，我想让他高度为100%，就用了
```
baidu-map{
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
}
```

**Comment by leftstick** [comment]
那要不是显示指定下`width: 100%; height: 100%`试试？

**Comment by F5F5** [comment]
@leftstick flex1元素的子元素设置height:100%无效...

**Comment by leftstick** [comment]
那大概是这个意思了，地图要求宽高是固定值，我猜你现在写四一个宽高，譬如：`width: 500px; height: 400px`。
然后再随意切换下路由，问题可能就没了

**Comment by leftstick** [comment]
是的，我也就是让你确认下问题，哈哈。具体解决方案，你只能自己探索了(逃)

**Comment by F5F5** [comment]
Map的```option```配置
```
      enableAutoResize: true
```
## 解决
