### ISSUE TITLE
如何加载其他百度地图的插件？

### ISSUE THREAD

**Issue by F5F5** [leftstick/angular2-baidu-map#37]
### [百度地图插件库地址](http://lbsyun.baidu.com/index.php?title=open/library)

是修改```angular2-baidu-map\dist\src\providers\scriptLoader.js```这个文件吗？可以这么做不：

在```appendScriptTag(MAP_URL);```后面加入
```
appendScriptTag('http://api.map.baidu.com/library/RichMarker/1.2/src/RichMarker_min.js');
```

但是报错。。。
```
Uncaught ReferenceError: BMap is not defined
```

**Comment by leftstick** [comment]
目前不是，我还没有想好插件以什么形式进入。这个恐怕得等我再想想了

**Comment by leftstick** [comment]
新版本发布，目前仅支持`<heatmap />`，详情，看[文档](https://leftstick.github.io/angular2-baidu-map/#/apidoc/heatmap)。

至于其他插件，还在计划中
