### ISSUE TITLE
ERROR in Metadata version mismatch for module /Volumes/work/angularjs_proj/test/angular4-primeng-demo/node_modules/angular2-baidu-map/dist/src/index.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by nicholasalx** [leftstick/angular2-baidu-map#38]
ERROR in Metadata version mismatch for module /Volumes/work/angularjs_proj/test/angular4-primeng-demo/node_modules/angular2-baidu-map/dist/src/index.d.ts, found version 4, expected 3

**Comment by kuangYIN1217** [comment]
I have the same question. my ng is 4.4.6

**Comment by leftstick** [comment]
This module was built on top of `angular-5.0.1`, this might be the issue. I think you need to upgrade your `angular` to latest version

**Comment by kuangYIN1217** [comment]
how to upgrade angular version?I tried a lot of methods, but they were all wrong

**Comment by ytlSdk** [comment]
@leftstick 项目中 好多插件都是基于angular4.x 如果将angular版本升到5.0的话  更多插件不能用用了 angular2-baidu-map如何能做到兼容angular4.x?

**Comment by leftstick** [comment]
@kuangYIN1217  depends on how you install `angular` as your dependency? If you are using `npm`,     you may use `npm i --save @angular/core@5.0.5` to upgrade.

@ytlSdk  除非我这边给库做降级处理，但不清楚那些用了`^5.x`版本的小伙伴会不会因此而挂，所以我得慎重考虑下。或者你可以fork项目自己做降级，你的项目就依赖你的fork

**Comment by ytlSdk** [comment]
@leftstick  我试试 不过你的原始项目 ng build 出来是 demodist, 估计改动会比较大吧

**Comment by leftstick** [comment]
@ytlSdk 输出结果用`npm run dist`。

**Comment by leftstick** [comment]
@nicholasalx @kuangYIN1217 it is known [issue](https://github.com/angular/angular/issues/19607), upgrade your `angular` dependencies to latest version should be the best way for now

**Comment by kuangYIN1217** [comment]
@leftstick  Thank you. I'm try

**Comment by nicholasalx** [comment]
thank you！




| |
David
|
|
邮箱：nicholas_jsj@126.com
|

签名由 网易邮箱大师 定制

On 12/06/2017 14:58, kuangYIN1217 wrote:

@leftstick Thank you. I'm try
