### ISSUE TITLE
Addition to Geolocation component

### ISSUE THREAD

**Issue by zzpmaster** [leftstick/angular2-baidu-map#4]
According to the baidu map api, it have a component is GeolocationControl. it can implementation positioning function. [GeolocationControl](http://developer.baidu.com/map/reference/index.php?title=Class:%E6%8E%A7%E4%BB%B6%E7%B1%BB/GeolocationControl) and [GeolocationControlOptions](http://developer.baidu.com/map/reference/index.php?title=Class:%E6%8E%A7%E4%BB%B6%E7%B1%BB/GeolocationControlOptions)

i hope to get your help and add geolocationCtrl attribute in MapDefaultOptions and it can set GeolocationControlOptions, I feel it is necessary.
```
export interface MapDefaultOptions {
    navCtrl?: boolean;
    geolocationCtrl?: any;
    overviewCtrl?: boolean;
    enableScrollWheelZoom?: boolean;
    zoom?: number;
}
```

Do you have any good suggestion? thank you. 
waiting for your reply

**Comment by leftstick** [comment]
This seems a nice feature, and supported in `2.3.0`, have fun with it. and if you have problem, feel free to open issue here

**Comment by zzpmaster** [comment]
Thank you very much
