### ISSUE TITLE
报错 Metadata version mismatch

### ISSUE THREAD

**Issue by yaoqr15** [leftstick/angular2-baidu-map#40]
Metadata version mismatch   found version 4, expected 3，请问是angular版本不符合要求还是别的情况呢？

**Comment by leftstick** [comment]
`angular-5.x`的[已知问题](https://github.com/angular/angular/issues/19607)。`angular2-baidu-map`是用`angular-5.x`的`compiler`编译的，你的代码依赖的应该是`<=angular-4.x`的版本。

升级你的依赖到`angular-5.x`就好了

**Comment by yaoqr15** [comment]
那如果是使用3.x版本的angular2-baidu-map 能够匹配吗？还是说3.x依然基于angular5来开发的

**Comment by leftstick** [comment]
`3.x`的`angular2-baidu-map`是`angular-4.x`的`compiler`没错。不过那个版本以后不会再维护了(因为各种我之前的设计缺陷)。

而且据`angular`官网描述，`angular-5.x`是兼容之前版本的，所以理论上你把自己的依赖升级到`angular-5.x`是没有问题的
