### ISSUE TITLE
组件仅支持添加marker覆盖物吗？

### ISSUE THREAD

**Issue by tainchuisiye** [leftstick/angular2-baidu-map#41]
看了下源码，发现覆盖物中只有marker，其他的要自己写吗？期待大神更新。

**Comment by leftstick** [comment]
目前只有`marker`，其他你还想要什么呢？

**Comment by panpan0000** [comment]
比如是否考虑封装定位控件？
另外大牛给个例子，怎么在angular2-baidu-map上使用路径规划功能？

**Comment by leftstick** [comment]
@tainchuisiye 新版本发布, `4.2.0`，新增不少组件。


@panpan0000 关于定位控件，试试如下手段：

```html
<baidu-map [options]="opts">
      <control type="geolocation" [options]="controlOpts"></control>
</baidu-map>
```

详情，看[文档](https://leftstick.github.io/angular2-baidu-map/#/apidoc/control)
