### ISSUE TITLE
Ionic 3.9.2 | Angular 5.0.0

### ISSUE THREAD

**Issue by pierresh** [leftstick/angular2-baidu-map#44]
Hello,

The latest release of Ionic uses Angular 5.0.0, while this module requires Angular 5.0.1 and above (and its previous version requires Angular below 5..). I would like to know if it is possible to force the installation of this module with Angular 5.0.0 so that I could use it with Ionic. Thanks!

**Comment by pierresh** [comment]
Actually, I ignored the warnings given by npm and it works.

**Comment by leftstick** [comment]
correct, `peerDependencies` won't break your app from running
