### ISSUE TITLE
[IE 10 compatibility ]

### ISSUE THREAD

**Issue by ray525** [leftstick/angular2-baidu-map#45]
## verison
![image](https://user-images.githubusercontent.com/8563684/35429457-194ad97c-02af-11e8-9a27-bdb2af7bc935.png)

## polyfills.ts
>/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

## Repro steps
> ng new myapp
ng serve --no-live-reload

## observed behavior

![image](https://user-images.githubusercontent.com/8563684/35429128-a1a02202-02ad-11e8-8983-d6abc7d218b1.png)

![image](https://user-images.githubusercontent.com/8563684/35429140-b72f24f6-02ad-11e8-8168-2f42670f0161.png)

## Desired behavior
should work with it 10

## Mention any other details that might be useful
https://github.com/angular/angular-cli/issues/8596

**Comment by leftstick** [comment]
please try `4.1.1`
