### ISSUE TITLE
需要支持发布目标为es5

### ISSUE THREAD

**Issue by thm1118** [leftstick/angular2-baidu-map#46]
ios8 浏览器不支持 es6，因此依赖当前npm发布包 ，会导致在ios8 上无法运行。

**Comment by leftstick** [comment]
@thm1118 能否调试一下，告诉我哪个函数，或者属性在iOS8里报错了？

**Comment by thm1118** [comment]
哈， mac太老了，丢家里都不想开， 所以没法具体定位问题。 之前发现有诸如 const语法会导致报错。

**Comment by thm1118** [comment]
ionic3 发布包只有es5，甚至没有es6等可选项。或许可以参考下angular打包规范

**Comment by thm1118** [comment]
[Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview)
[Angular libraries are fun](https://medium.com/spektrakel-blog/angular-libraries-are-fun-fece73cceb05)
[Building an Angular 4 Component Library with the Angular CLI and ng-packagr](https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e)
看到这几篇文章和angular打包相关。

**Comment by thm1118** [comment]
http://kangax.github.io/compat-table/es6/  里，设置选中 Show obsolete platforms， ios8 只支持17%的es6语法， ios9是53%，知道ios10才有很大改善。 IE10,11更是惨不忍睹。 #45 估计也是类似问题
定位某些问题试图兼容看起来挺困难。

**Comment by thm1118** [comment]
我就直接pr啦

**Comment by leftstick** [comment]
那个`ng-packager`的问题还是没搞定，我最近也没时间研究那个东西，你有兴趣可以继续看下。

我现在用老办法输出了ES5 code，理论上之前的问题应该解决了。


后面如果你有兴趣，可以帮我看看demo里引用`ng-packager`编译出的内容到底哪里不对，操作步骤：

先打开`package.json`，修改其中的`main`，`types`字段为：

```
"module": "./dist/esm5/angular2-baidu-map.js", 
"es2015": "./dist/esm2015/angular2-baidu-map.js", 
"main": "./dist/bundles/angular2-baidu-map.umd.js", 
"typings": "./dist/angular2-baidu-map.d.ts"
```

用，`npm run packager`生成dist目录

打开`demo`目录，搜索所有的`/src`字符串，全部替换为`/`，然后运行`npm start`查看结果（我现在这一步是报错的，没时间继续看了，为大家方便，先用原方式提供新版本吧）。
