### ISSUE TITLE
auto-display the InfoWindow

### ISSUE THREAD

**Issue by xiabin1235910** [leftstick/angular2-baidu-map#5]
Hi, leftstick
I suggest to add a new small feature about auto-display the InfoWindow.
For now, I find that only after clicking the marker, the InfoWindow appears.

So how about the follow?
```
        // add default behavior...
        if(marker.auto_display) {
            marker2.openInfoWindow(infoWindow2);
        }
```

**Comment by leftstick** [comment]
Nice feature, i will consider to add it in next release

**Comment by zzpmaster** [comment]
Good idea。

**Comment by leftstick** [comment]
Please upgrade to `2.4.0`
