### ISSUE TITLE
how about to use GeolocationControlOptions

### ISSUE THREAD

**Issue by debin168** [leftstick/angular2-baidu-map#55]
i want to implement  autolocal postion  when loaded ,but i can't found any function can implement it .

i use follow code  
   <control type="geolocation" [options]="geolocationOpts"   (loaded)="onLocation($event)" ></control>
it only display a local icon, it can local position when i click it . but how to implement auto local positon   when the map loaded.  can u give me  some suggestion?

**Comment by debin168** [comment]
great! thank you

**Comment by leftstick** [comment]
Try `4.2.1`, just released.

```html
<baidu-map [options]="opts">
      <control type="geolocation" (loaded)="controlLoaded($event)"></control>
</baidu-map>
```

```typescript
export class DemoComponent {
  public opts: MapOptions

  constructor() {
    this.opts = {
      centerAndZoom: {
        lat: 31.244604,
        lng: 121.51606,
        zoom: 16
      }
    }
  }

  public controlLoaded(control: BGeolocationControl): void {
    // 你要的自动定位
    control.location()
  }
}
```

**Comment by debin168** [comment]
谢谢你的帮助，我在PC尝试了一下，没有效果，稍后我再在手机上尝试下，看是不是因为PC的原因，所以无法定位。
