### ISSUE TITLE
请问支持gps原始坐标转成百度坐标吗

### ISSUE THREAD

**Issue by hmukan** [leftstick/angular2-baidu-map#56]
目前坐标转换支持吗？

能否使用 BMap.Convertor();来完成坐标转换？

**Comment by leftstick** [comment]
坐标准换听起来感觉通过声明式的组件来提供并不是个好选择，你从loaded事件里拿到map实例后自己调用上面的函数应该更方便吧？

**Comment by hmukan** [comment]
拿到map实例后，怎么调用的？
我用下面的调用方式，控制台提示：ERROR TypeError: Cannot read property 'translate' of undefined(…)
onLoaded(map: any) {
        console.log(map);
        map.convertor.translate({lon:113.925437, lat:22.679228}, 1, 5, this.tranToBDPointCallback);
 }

tranToBDPointCallback(data) {
}

**Comment by hmukan** [comment]
console.log(map.convertor);
//输出是：undefined

**Comment by leftstick** [comment]
拿到实例后其实就是百度地图api的事了，我没做任何封装，我去看了下，你用法不对。

```typescript
  public onLoaded() {
    var convertor = new window.BMap['Convertor']()
    convertor.translate([new window.BMap.Point(116.32715863448607, 39.990912172420714)], 1, 5, data => {
      console.log('转换完毕', data)
    })
  }
```

![converter](https://user-images.githubusercontent.com/1059956/38765262-efa69b68-3ff0-11e8-91cd-d0a8cf195a6c.gif)

**Comment by wenyangliu** [comment]
您好，请问页面刷新报错怎么解决
![tim 20180621200301](https://user-images.githubusercontent.com/20938493/41718078-6dba8f78-758e-11e8-9e3e-7ef2d095ab94.png)

**Comment by wenyangliu** [comment]
我这边从其他路由跳转可以获取window.BMap,在本页面刷新打印window里面有BMap属性，但是window.BMap就是undefined了

**Comment by leftstick** [comment]
代码贴出来，还有，你最好新开一个帖子说你的问题。不要在别人的已关闭的issue里讨论你的问题
