### ISSUE TITLE
在ionic3中使用这个组件时，clicked 小概率触发事件，大概率没有反应

### ISSUE THREAD

**Issue by winds1987** [leftstick/angular2-baidu-map#57]
angular/core": "5.2.9",
 "angular2-baidu-map": "^4.2.1",
"ionic-angular": "3.9.2",

在ionic3中使用这个组件时，clicked 小概率触发事件，大概率没有反应，不知道怎么回事。
![image](https://user-images.githubusercontent.com/9546433/39620425-b237b62c-4fbd-11e8-95c6-9d3ed8afc093.png)

ionic3中，不是 button和a 标签的话，触发click会有延时，不知道是不是这个导致的

**Comment by leftstick** [comment]
`clicked`小概率触发，你是指， `<baidu-map />`上的？还是`<marker />`上的？没用过`ionic`系列，不好说，不过因为所有`clicked`事件都是对百度地图自己api的封装，百度地图是肯定没在自己元素上加`tapable`的，所以延迟有可能，没触发的话，就需要你提供更多信息来推断了。

**Comment by wangdaokuan** [comment]
您好 我也遇到类似的问题了 请问解决了吗？

**Comment by winds1987** [comment]
我刚刚新建了一个demo测试了下，好像没有问题了。测试版本如下：
"@angular/core": "5.2.11",
"@ionic-native/core": "~4.18.0",
"ionic-angular": "3.9.2",
"angular2-baidu-map": "^4.5.0",

ionic : 4.6.0，

不知道是作者修复了，还是ionic升级后就没有这个问题了。

不过当时那个项目中，没有找到解决办法，所以没有用这个组建，直接用的原生 API。
