### ISSUE TITLE
Cannot find the imageSize property of the Icon ?

### ISSUE THREAD

**Issue by wyw20123wyw** [leftstick/angular2-baidu-map#58]
你好，Icon属性里没有封装imageSize属性，我该怎么设置？或者有没有可能添加上

**Comment by leftstick** [comment]
在`4.2.1`里icon是可以设置大小的，参考文档[icon](https://leftstick.github.io/angular2-baidu-map/#/apidoc/icon)

![screen shot 2018-05-08 at 5 15 37 pm](https://user-images.githubusercontent.com/1059956/39748777-9525bfec-52e3-11e8-9424-6fc21c34fc99.png)


具体使用的例子，可以参考[marker](https://leftstick.github.io/angular2-baidu-map/#/apidoc/marker)

代码如下：

```typescript
export class DemoComponent {
    public opts: MapOptions
    public markers: Array<{ point: Point; options?: MarkerOptions }>
  
    constructor() {
      this.opts = {
        centerAndZoom: {
          lat: 31.244604,
          lng: 121.51606,
          zoom: 16
        }
      }
  
     //markerOptions里可以通过icon来设置自定的marker图标，里面的size使用方式
      this.markers = [
        {
          options: {
            icon: {
              imageUrl: '/assets/markericon.png',
              size: {
                height: 60,
                width: 50
              }
            }
          },
          point: {
            lat: 31.244604,
            lng: 121.51606
          }
        },
        {
          point: {
            lat: 31.246124,
            lng: 121.51232
          }
        }
      ]


    }
  
    public showWindow({ e, marker, map }: any): void {
      map.openInfoWindow(
        new window.BMap.InfoWindow('地址：浦东南路360号', {
          offset: new window.BMap.Size(0, -30),
          title: '新上海国际大厦'
        }),
        marker.getPosition()
      )
    }
  }  
```

**Comment by wyw20123wyw** [comment]
是百度API文档里面的imageSize，而不是size
![image](https://user-images.githubusercontent.com/24589934/39749341-04fd79da-52e5-11e8-9ab7-5e00dd4dff92.png)

**Comment by leftstick** [comment]
这个似乎的确没有，我稍后抽时间看下是否能支持（当初为什么没加有点忘了，可能有什么特殊情况）。

**Comment by leftstick** [comment]
@wyw20123wyw 能讲下你使用`imageSize`的场景么？因为百度文档里`imageSize`只能通过`setImageSize`方法来设置，我必须从你的使用场景里考虑如何设计这个部分

**Comment by leftstick** [comment]
如果你是想构造`marker`的时候设置其`icon`的`imageSize`，那试试`4.3.0`吧，新增了. [icon](https://leftstick.github.io/angular2-baidu-map/#/apidoc/icon)

**Comment by wyw20123wyw** [comment]
十分不好意思，刚看到。我使用场景就是想在构造marker的时候设置icon的imageSize属性。辛苦了，非常感谢！！！👍👍👍
