### ISSUE TITLE
reset map on ngDestroy

### ISSUE THREAD

**Issue by subarroca** [leftstick/angular2-baidu-map#6]
This happens when:

1. enter the component holding the map
2. leave the component
3. enter again

Map is considered already loaded but it does not exist anymore so setCenter throws an error

```
browser_adapter.ts:82 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:82ExceptionHandler.call @ exception_handler.ts:74(anonymous function) @ application_ref.ts:374schedulerFn @ async.ts:148SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:133onError @ ng_zone.ts:142onHandleError @ ng_zone_impl.ts:95ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.ts:105NgZone.runGuarded @ ng_zone.ts:225outsideHandler @ dom_events.ts:20ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.ts:82 TypeError: Cannot read property 'setCenter' of undefined
    at Object.exports.reCenter (angular2-baidu-map.js:235)
    at BaiduMap.ngOnChanges (angular2-baidu-map.js:93)
```

**Comment by xiabin1235910** [comment]
I write an example.  Please refer to [https://github.com/xiabin1235910/example-angular2-baidu-map](url)

**Comment by subarroca** [comment]
Thanks xiabin, but I was aiming for an easier way, just defining an options object in my component and assigning it to the attribute in html, just like in the given demo of this repo.
Not destroynig the map reference after removing it from the screen should be considered a bad practice and that was what I was asking for

**Comment by xiabin1235910** [comment]
In my opinion, The 'angular2-baidu-map' is just like an adapter to dynamically load the script -- 'http://api.map.baidu.com/api?v=2.0&ak=${ak}&callback=baidumapinit'. 
So when you leave the component, the angular2 will automatically collect the rubbish. 

Just like when you use the following script in normal html.
<script src='http://api.map.baidu.com/api?v=2.0&ak=${ak}&callback=baidumapinit'></script>

When you leave the page and enter again, the script will load again.

The 'loadMap' method can be triggered by the output emitter 'onMapLoaded', when the baidu-map script has been loaded completely.

**Comment by subarroca** [comment]
the thing is a window property is touched after the map is inited. Unless you clean this variable that it's outside the angular loop, the next time you load the map won't work. This is because it checks if the var is inited, so I had to do that manually, but I think that should be moved inside de destruction of angular2-baidu-map component

**Comment by andyli5527** [comment]
I also encountered this problem. subarroca, how to  clean this variable that it's outside the angular loop. Could you make a example.

**Comment by leftstick** [comment]
This is caused by the misunderstood of `OnInit` interface. I was expecting that `ngOnInit` will be called whenever the component is mounted. But the fact is not. Let see following docs:

<img width="685" alt="screen shot 2016-07-29 at 9 09 11 pm" src="https://cloud.githubusercontent.com/assets/1059956/17249059/b95b1b94-55d0-11e6-8f40-a4ba5bb29613.png">

Please feel free to have a trial with `2.4.1`, and if you like, you can try with [online-demo], toggle the <img width="44" alt="screen shot 2016-07-29 at 9 12 05 pm" src="https://cloud.githubusercontent.com/assets/1059956/17249165/3439f2c2-55d1-11e6-9e41-f6eb50b1d723.png"> button to mount/unmount the map.

>Do not click any other option update button, since they may modify the options and break the mount/unmount function
