### ISSUE TITLE
聚合点点击抖动

### ISSUE THREAD

**Issue by baoom10** [leftstick/angular2-baidu-map#65]
聚合点点击，进入聚合的点的部分，页面抖动厉害，是两个方向的抖动一下，案列里的聚合点也是一样，刷新到5个点以上，很容易出现抖动

**Comment by leftstick** [comment]
我在百度官网的例子里试了下，很蛋疼，也有这个问题[clusterer-example](http://api.map.baidu.com/library/MarkerClusterer/1.2/examples/simple.htm)，所以应该不是有angular引起的
