### ISSUE TITLE
地图不显示了，但是刷新页面可以显示

### ISSUE THREAD

**Issue by forcde** [leftstick/angular2-baidu-map#66]
我在首页放的地图，登陆进入首页的时候，地图可以显示，但是我点击侧边其他导航条，然后在点击回到首页的时候，地图不显示了

 对比了一下地图可以显示的时候
1.多了一个一个css属性，style display block    <div _ngcontent-c18="" class="baidu-map-instance" style="display: block; 
2.多了一个div  class="BMap_mask"

前端小白

**Comment by leftstick** [comment]
请提供你首页里是如何引用，并使用组件的代码

**Comment by LiHuiNeng** [comment]
你好，请问解决了吗？能否说一下解决方法！谢谢 :)
