### ISSUE TITLE
这个库有没有提供一些百度地图api的调用，比如geocoder,LocalSearch等等

### ISSUE THREAD

**Issue by vieri68** [leftstick/angular2-baidu-map#68]

**Comment by leftstick** [comment]
是的，这类和UI无关的命令式操作，我始终没想好如何通过组件暴露出来。所以现阶段最直接的办法就是在

`<baidu-map [options]="expression" (loaded)="mapLoaded"></baidu-map>`

的`loaded`事件回调里直接使用，譬如：

```typescript

mapLoaded (map: any) {
   new window.BMap.LocalSearch(map, {
	renderOptions:{map: map}
  });
  local.search("景点");
}

```

**Comment by 270sun** [comment]
对于LocalSearch，是可以做一个与UI相关的，比如地址搜索框，通过这个来搜索或者解析地址。可以参考ngx-google-places-autocomplete
