### ISSUE TITLE
这个百度默认v2版本可以升到v3？官方demo里又个CanvasLayer？好像我们这个插件里没有这个类

### ISSUE THREAD

**Issue by baoom10** [leftstick/angular2-baidu-map#71]

**Comment by leftstick** [comment]
完全可以升级到`v3`，我抽时间搞下就行。

`CanvasLayer`没用过，有时间我想想看怎么弄进来。之前似乎也只实现了`tileLayer`和`trafficLayer`两个类。

感谢建议和关注

**Comment by leftstick** [comment]
@baoom10 已经升级到`v3`，不过`CanvasLayer`还没做

**Comment by leftstick** [comment]
@baoom10  发布了`4.5.0`，新增了`canvaslayer`，看[这里](https://leftstick.github.io/angular2-baidu-map/#/apidoc/canvaslayer)
