### ISSUE TITLE
怎么使用自定义覆盖物

### ISSUE THREAD

**Issue by Kohcer** [leftstick/angular2-baidu-map#72]
请问使用这个插件如何使用自定义覆盖物

**Comment by Kohcer** [comment]
MapService这个服务只能通过元素使用么

**Comment by leftstick** [comment]
组件目前支持的覆盖物，其实就是文档里写的那几样(精力有限，支持的数量并不多)：

![screen shot 2018-09-05 at 5 48 55 pm](https://user-images.githubusercontent.com/1059956/45085734-fe23af00-b133-11e8-812d-b633f950051f.png)


如果你继续其他覆盖物，目前只能通过`<baidu-map  (loaded)="expression" />`  上的`loaded`事件，拿到原始的百度地图实例，然后通过参照百度地图文档自己添加其他覆盖物

**Comment by Kohcer** [comment]
感谢回答。考虑项目维护的问题已经，自己写了个服务去维护了。毕竟写在loaded事件上会降低灵活。
