### ISSUE TITLE
polyline 添加points不实时更新，可否有刷新地图的功能呢？

### ISSUE THREAD

**Issue by kzsense** [leftstick/angular2-baidu-map#73]
如题，想根据用户行进的路上实时更新添加polyline的points, 但是添加后页面无变化。。应该是因为polyline已经loaded了所以不会实时更新的缘故吧。。有什么解决办法吗？

**Comment by leftstick** [comment]
能给我个showcase么？我看下具体是个怎么样的操作场景

**Comment by kzsense** [comment]
当然，我现在在做一个跑步的app，可以根据用户的移动在地图上画出轨迹的，目前我看了下好像polyline最符合我的需求。
所以我大概每5-10秒左右会获取一次用户的baidumap_location的data, 然后把这个data pass到baidumap里面更新baidumap的marker的point和在polyline的points里面添加point。
![wechatimg96](https://user-images.githubusercontent.com/38581231/45333531-48c87f80-b5a9-11e8-9a81-d2f75f61bc92.jpeg)
上图这个是我想要达到的画轨迹的效果。但是我不确定这个是用的polyline么？

[http://kasheftin.github.io/gmaps/](url)
这个是我找到的一个比较不错的google polyline的demo，还蛮不错的，但是和上面那张的轨迹样式有很大的差距，如果做不到上面那样，我至少能做成这样的也可以。

![wechatimg97](https://user-images.githubusercontent.com/38581231/45333632-d73d0100-b5a9-11e8-9369-df5fd0ae8655.jpeg)
实际上这个是我目前达到的，问题主要有3个：
1. 我用了setInterval每3秒给polyline的points增加point，但是polyline不reload.
2. polyline的起始点和marker的point是一模一样的位置，但是他们明显不在一个点上，这是为啥。。
3. 我的polyline的样式和我第一张图中的有很大的区别。我不知道是我用错了方法还是别人美化的样式呢？

望给点启发，十分感谢，我在地图方面实属新手。。

**Comment by kzsense** [comment]
好我现在试，稍等

**Comment by kzsense** [comment]
可以了！！！！十分感谢！！！请问可以解答一下为什么polyline画不出图1中的效果么。。是因为他们美化了polyline吗？

**Comment by leftstick** [comment]
options似乎也调节不了线的样式，我估计那是主题上的问题了，我现在没具体概念，没法回答你

**Comment by kzsense** [comment]
好的。。十分感谢。。目前还有一个问题就是marker的point的位置和polyline的起点如出一辙，但是位置的显示却截然不同
![1](https://user-images.githubusercontent.com/38581231/45335368-9812ae00-b5b1-11e8-861d-198e2ac25444.jpeg)
这张是用默认的map pin。

![2](https://user-images.githubusercontent.com/38581231/45335380-a8c32400-b5b1-11e8-851b-34614dbe70f7.jpeg)
这张是用我customize过后的map pin。

我把你demo中那个infowindow的offset去掉了，然后这个infowindow指向的位置就是polyline起始的位置，而2个marker的标记距离这个位置差了很多，这是为什么呢。。？
