### ISSUE TITLE
无法动态改变MARKER的ICON

### ISSUE THREAD

**Issue by hanying33** [leftstick/angular2-baidu-map#74]
我想先生产一系列的marker,然后通过用户做某些操作去改变对应marker的icon的imageurl. 

我试了在marker（loaded)的时候将marker放进一个JSON里面
`this.markerList[the_id] = marker;`
等用户点了页面某个元素（非地图元素）后从JSON里拿出对应的marker，然后试了下面两种方法，都没有用：
1. `this.markerList[selected_id].getIcon().setImageUrl('path/to/new/imagefile')`
2. `this.markerList[selected_id].setIcon(new window.BMap.Icon('path/to/new/imagefile', new window.BMap.Size(80,80)))`
我猜测是marker放进 markerList 里之后再拿出来做改动，改动已经不是针对原始的marker对象了。所以我在 （loaded)的function里直接试了上面两种方法，地图也没有任何改动。

另外，为了验证setIcon(), setImageUrl()方法是否正常，我试了(clicked)的时候，对通过event传进来的marker对象的icon做改变。用了以下两种方法，方法2可以改变MARKER的ICON，方法1不可以。
1. `marker.getIcon().setImageUrl('path/to/new/imagefile')`
**2. `marker.setIcon(new window.BMap.Icon('path/to/new/imagefile', new window.BMap.Size(80,80)))`**

请问有什么办法可以动态改变MARKER的ICON吗？ 在线等，谢谢！
我用的是ANGULAR 6

**Comment by leftstick** [comment]
`<marker loaded="" />` 得到的就是百度地图原生的`marker`实例，按理说`this.markerList[selected_id].setIcon(new window.BMap.Icon('path/to/new/imagefile', new window.BMap.Size(80,80)))`这个操作是没有问题的，这个我可能需要找时间再研究一下了

**Comment by leftstick** [comment]
最好的办法是直接修改原先`MarkerOptions`的`icon`属性，例如：

初始化的markerOptions

```typescript
this.markers = [
      {
        options: {
          icon: {
            imageUrl: `地之一`,
            size: {
              height: 35,
              width: 25
            },
            imageSize: {
              height: 35,
              width: 25
            }
          }
        },
        point: {
          lat: 31.244604,
          lng: 121.51606
        }
      }
    ]
```

更改属性：

```typescript
this.markers = [
      {
        options: {
          icon: {
            ...this.markers[0].options.icon,
            imageUrl: `地址二`
          }
        },
        point: {
          ...this.markers[0].point
        }
      }
    ]
```

**Comment by elevensheep** [comment]
现在在loaded函数中已经可以修改了
