### ISSUE TITLE
可以实现ANIMATION吗

### ISSUE THREAD

**Issue by hanying33** [leftstick/angular2-baidu-map#75]
我想在用户HOVER ON 某个非地图元素的时候，给对应的MARKER添加BOUNCE ANIMATION，请问可以怎么实现呢？

**Comment by leftstick** [comment]
最近比较忙，兼顾这边的时间有限。能否提供一个例子，如果用原生的地图api，你要的功能怎么做？

**Comment by hanying33** [comment]
我想要MARKER的setAnimation()这个方法，我看源码好像没有这个接口。

`marker.setAnimation($window.BMAP_ANIMATION_BOUNCE);`

**Comment by leftstick** [comment]
已增加，请尝试使用1`4.4.0`
