### ISSUE TITLE
how to use clearOverlays

### ISSUE THREAD

**Issue by pierresh** [leftstick/angular2-baidu-map#83]
Hello,

I would like to update the position of a marker on the map. Loading a new array of markers does not remove the markers displayed previously. I suppose I need to use the function _map.clearOverlays_ but I could not figure out how to call it.. Thanks!

**Comment by leftstick** [comment]
It should be handle internally in `<marker />` component, if it was not working, would you provide me an example for your case?

**Comment by pierresh** [comment]
Hello, thanks for your feedback. Actually, I am sorry but it finally works ^^.

**Comment by pierresh** [comment]
Hello,

I re-open this issue because I meet a related issue with polyline. Actually I want to display a polyline between my current position and the destination. It works fine but when my location is updated, a new polyline is displayed but previous polyline is still displayed, even when I set the option _enableMassClear_ to **true**. Nevertheless, when I move the map, previous polylines get deleted and the display is eventually as expected.

Below is my code:

```
public line_points: Array<Point> = [];
public polylineOptions: PolylineOptions;

[...]

this.polylineOptions = {
	strokeColor: 'blue',
	strokeWeight: 2,
	enableMassClear: true
}

[...]

computeDistance() {
	this.line_points = [];
	if (this.last_lng != undefined) {
		this.line_points = [
			{
				lat: this.target_lat,
				lng: this.target_lng
			}, {
				lat: this.last_lat,
				lng: this.last_lng
			}
		]
	}
	[...]
}

[...]

<baidu-map 	[options]="options" 
		style="display: block; width: 100%; height: calc(100% - 55px);">
	<control type="navigation"></control>
	<polyline [points]="line_points" [options]="polylineOptions"></polyline>
</baidu-map>
```

**Comment by leftstick** [comment]
See my example: [https://leftstick.github.io/angular2-baidu-map/#/apidoc/polyline](https://leftstick.github.io/angular2-baidu-map/#/apidoc/polyline)

![mapdemo](https://user-images.githubusercontent.com/1059956/48309758-52775f00-e5bb-11e8-8b50-1649cdbf28ac.gif)

**Comment by pierresh** [comment]
I know how to draw a polyline, the problem is that when I updated it when I move, previous polyline are not cleared. Please attached picture:

![wechatimg448](https://user-images.githubusercontent.com/7520095/48309780-ca458980-e5bb-11e8-911c-02fd07b0647f.jpeg)
