### ISSUE TITLE
How to Use getDistance() method?

### ISSUE THREAD

**Issue by hassansheikh** [leftstick/angular2-baidu-map#84]
i am trying to to find distance from one point to another point.In getDistance method is pass two parameters start point and end Point but it gives me Error "ERROR TypeError: Object doesn't support property or method 'fc'".

**Comment by leftstick** [comment]
@hassansheikh can you provide me an example for your case? I'd like to see the scenarios

**Comment by hassansheikh** [comment]
Here is my Code for Get Distance
Home.html Page
`<ion-header>
  <ion-navbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content padding>
<baidu-map [options]="opts" (loaded)="getMapInstance($event)">
</baidu-map>
</ion-content>`

Home.ts
`import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Animation, MapOptions, BMarker, BMapInstance, MarkerOptions, Point } from 'angular2-baidu-map';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  public opts: MapOptions
  public Bmap: BMapInstance;

  public start: Point;  
  public end: Point;

  constructor(public navCtrl: NavController) {

this.opts = {
      centerAndZoom: {
        lat: 31.244604,
        lng: 121.51606,
        zoom: 16
      }
    }

  }

public getMapInstance(map): void {
    this.Bmap=map;
    this.end={
		lat: 31.244604,
        lng: 121.51606}
	this.start={
		lat: 31.500433,
        lng: 121.52467}

    this.Bmap.getDistance(this.start,this.end);
  }
}
`

**Comment by leftstick** [comment]
@hassansheikh try following:

```typescript
public getMapInstance(map: BMapInstance): void {
    const end = new window.BMap.Point(121.51606, 31.244604)
    const start = new window.BMap.Point(121.52467, 31.500433)

    console.log(map.getDistance(start, end))
}
```
