### ISSUE TITLE
How can i show Route on map from one location to another?

### ISSUE THREAD

**Issue by hassansheikh** [leftstick/angular2-baidu-map#85]
i do not find any thing in this library.can i how route from one location to an other?

**Comment by leftstick** [comment]
It's currently not supported natively by `angular2-baidu-map`, i am trying to figure how would the route component looks like.

As a workaround,  you can write it in your own code with `map` instance from `loaded` event

**Comment by hassansheikh** [comment]
i am very much familiar  with this. Can you please guide me how to implement route with map instance from loaded event or can you please give me example code for this.
