### ISSUE TITLE
Problem When Create Build in production mode

### ISSUE THREAD

**Issue by hassansheikh** [leftstick/angular2-baidu-map#87]
is working well in development mode.
when i try to create build with --prod it gives error

Error: Metadata version mismatch for module
C:/Ionic/Hamster_Updated/node_modules/angular2-baidu-map/angular2-baidu-map.d.ts, found version 4, expected 3

In Package.Json:
"angular2-baidu-map": "4.5.0",

Ionic INFO

Ionic:

   ionic (Ionic CLI)  : 4.2.1 (C:\Users\Hussnain\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.9

Cordova:

   cordova (Cordova CLI) : not installed
   Cordova Platforms     : android 6.4.0, browser 5.0.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.1.1, (and 19 other plugins)

System:

   Android SDK Tools : 26.1.1 (C:\Users\Hussnain\AppData\Local\Android\sdk)
   NodeJS            : v8.12.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.2.0
   OS                : Windows 10

**Comment by leftstick** [comment]
Please check what version of `@angular/core` you are using

**Comment by hassansheikh** [comment]
"@angular/core": "4.4.3"

**Comment by leftstick** [comment]
Same issue as [#38](https://github.com/leftstick/angular2-baidu-map/issues/38). 

The `angular2-baidu-map` is built via `@angular/core 5+`, but you are using `@angular/core 4.4.3`. You need upgrade your ng first
