### ISSUE TITLE
Map Control - map type option missing "mapTypes"

### ISSUE THREAD

**Issue by hanying33** [leftstick/angular2-baidu-map#88]
```
<baidu-map [options]="opts">
      <control type="maptype" [options]="mapTypeOpts"></control>
</baidu-map>
```

```
this.mapTypeOpts = {
        type: MapTypeControlType.BMAP_MAPTYPE_CONTROL_HORIZONTAL
}
```

Above code will show all three map types (地图，卫星，三维), but I don't want to show 三维. 
Can you allow adding "mapTypes" to "this.mapTypeOpts"?

**Comment by leftstick** [comment]
Upgrade to `4.6.0`, with following new option:

```typescript
this.mapTypeOpts = {
      type: MapTypeControlType.BMAP_MAPTYPE_CONTROL_HORIZONTAL,
      mapTypes: [MapTypeEnum.BMAP_NORMAL_MAP, MapTypeEnum.BMAP_SATELLITE_MAP]
}
```

see : [doc-control](https://leftstick.github.io/angular2-baidu-map/#/apidoc/control).

BTW, it's Chinese new year, why ru working so hard? 同九义汝何秀

**Comment by hanying33** [comment]
Haha, late Happy New Year @leftstick !
