### ISSUE TITLE
组建外部控制地图上的文本框

### ISSUE THREAD

**Issue by MyTrancy** [leftstick/angular2-baidu-map#89]
您好，很开心能用到这么方便的地图组件。
遇到的需求是组件外部按钮/单选框控制地图上文本（框）的显示隐藏。
看了演示得知文本框是创建出的` new window.BMap.InfoWindow`,发现好像也没有`label`或者`Infowindow`的组件。
故而请教该如何实现此需求

**Comment by leftstick** [comment]
对的，我在本库里没有封装提示框的功能，这个东东需要开发人员自己根据需求直接使用百度地图sdk的`InfoWindow` API来实现，你可以看[BMap.InfoWindow](http://lbsyun.baidu.com/cms/jsapi/reference/jsapi_reference_3_0.html#a3b7)来试试你需要什么功能

**Comment by MyTrancy** [comment]
好的，谢谢解答

**Comment by MyTrancy** [comment]
您好，请教个问题，想要给标记添加文本，用下边的方法
```
setLabel(marker: BMarker): void {
  marker.setLabel(  new BLabelConstructor('test', {}));
  }
```
但是会报错：`angular2-baidu-map`中`has no exported member 'Label'.`
和`error TS2693: 'BLabelConstructor' only refers to a type, but is being used as a value
 here.`

**Comment by leftstick** [comment]
try with `marker.setLabel(new window.BMap.Label('hello'))`

**Comment by MyTrancy** [comment]
可以了，谢谢~
那怎么不能直接`new Label('hello')`,而需要`new window.BMap.Label('hello')`
第一种new的时候不能自动导入，我是手动强行导入的🤦‍

**Comment by leftstick** [comment]
类型问题

**Comment by MyTrancy** [comment]
嗯嗯，我多注意，谢谢~

**Comment by MyTrancy** [comment]
遇到问题了😂，地图的参数是从数据库中拿，赋值是在`ngOnInit()`方法里边，然后就会提示这些参数是必须的，想到的解决办法是，在参数赋值之后在把`<baidu-map>`添加到页面,请问还有其他更好的解决方案么~

**Comment by MyTrancy** [comment]
解决了，创建参数变量时候赋予空值就好了😂

**Comment by leftstick** [comment]
nice
