### ISSUE TITLE
polyline component 可以加 CLICK EVENT吗？

### ISSUE THREAD

**Issue by hanying33** [leftstick/angular2-baidu-map#95]
polyline component 可以加 CLICK EVENT吗？

<polyline [points]="expression" [options]="expression" (loaded)="expression" (clicked)="expression"></polyline>

**Comment by leftstick** [comment]
sure [Polyline](https://leftstick.github.io/angular2-baidu-map/#/apidoc/polyline) 已支持，试下`4.7.0`
