### ISSUE TITLE
Marker拖拽无效，能够触发事件但是Marker本身没有移动

### ISSUE THREAD

**Issue by Remix1993** [leftstick/angular2-baidu-map#97]
我自己添加了dragstart dragging dragend 事件
调用了enabelDragging() 以后都能够正常触发，参数也正确，就是Marker位置不移动。
在调用了disableDragging()，以后就不触发了。

**Comment by leftstick** [comment]
有设置`enableDragging: true`么？如下：

![Screen Shot 2019-07-11 at 10 22 55 AM](https://user-images.githubusercontent.com/1059956/61017480-f07b2d80-a3c5-11e9-8363-b0242e7befbe.png)


设置之后，就可以移动了

![move](https://user-images.githubusercontent.com/1059956/61017508-07218480-a3c6-11e9-8eb3-57eb706384ab.gif)
