### ISSUE TITLE
热力图制作问题 版本信息:  "angular2-baidu-map": "^4.7.0",

### ISSUE THREAD

**Issue by LiHuiNeng** [leftstick/angular2-baidu-map#98]
源码中HeatmapPoint 的参数只有count好像没有lng和lat的参数。
这是官方文档中的:
![image](https://user-images.githubusercontent.com/37288957/60950967-b577ec00-a32a-11e9-9074-3c79dcda1850.png)
这是我本地环境中的：
![image](https://user-images.githubusercontent.com/37288957/60951015-ccb6d980-a32a-11e9-9e20-6aea95f67dde.png)
感谢回答问题!

**Comment by LiHuiNeng** [comment]
...继承了。

**Comment by LiHuiNeng** [comment]
很抱歉，我又打开了这个。希望作者解答，万分感谢！
按照官方demo，地图能够显示出来，但是热点并没有出现，并且报了一个错误。
component代码如下：
`this.options = {
      centerAndZoom: {     // 设置中心点和缩放级别
        lng: 113.11,   // 经度
        lat: 23.05,    // 纬度
        zoom: 8,         // 缩放级别
      },
      minZoom: 3,  // 最小缩放级别的地图
      maxZoom: 19, // 最大缩放级别的地图
      enableHighResolution: true,  // 是否用高分辨率的地图，default：true
      enableAutoResize: true,  // 是否可以自动调整大小，default：true
      enableMapClick: true,  // 地图是否可以点击，default：true
      disableDragging: false, // 是否禁用地图拖动功能
      enableScrollWheelZoom: true, // 是否启用滚轮进行缩放功能
      disableDoubleClickZoom: false, // 是否禁用双击缩放功能
      enableKeyboard: true,  // 是否启用键盘移动地图功能
      enableInertialDragging: false,     // 是否启用惯性阻力函数
      enableContinuousZoom: true,  // 是否启用连续缩放功能
      disablePinchToZoom: false,   // 是否禁用缩放功能的缩放
      cursor: '',         // 设置默认的光标样式,应该遵循CSS规范
    };
    this.heatData = [
      {
        lng: 116.387112,
        lat: 39.920977,
      }, {
        lng: 116.385243,
        lat: 39.913063
      }, {
        lng: 116.394226,
        lat: 39.917988,
      }, {
        lng: 116.401772,
        lat: 39.921364,
      }, {
        lng: 116.41248,
        lat: 39.927893,
      }
    ];
    this.heatmapOptions = {
      visible: true
    };

html代码如下：
<div style="display: block;height: 600px">
        <baidu-map [options]="options">
          <heatmap [dataset]="heatData" [options]="heatmapOptions" (loaded)="heatmapLoaded($event)"></heatmap>
          
          <control type="navigation" [options]="controlOpts"></control>
          
          <control type="overviewmap" [options]="overviewmapOpts"></control>
          
          <control type="scale" [options]="scaleOpts"></control>
          
          <control type="maptype" [options]="mapTypeOpts"></control>
          <control type="geolocation" [options]="geolocationOpts"></control>
        </baidu-map>
      </div>
`
浏览器出现错误：
![image](https://user-images.githubusercontent.com/37288957/60958412-e828e100-a338-11e9-93f8-6195ef212019.png)

万分感谢！！！

**Comment by LiHuiNeng** [comment]
你好，另外，还想再请教一下，地图窗口能在第一次加载时显示，但是路由切换后，回到地图界面时，就显示不出来,，窗口打印被销毁。 `on map destroy` ，我该如何再次加载地图呢？ (っ´Ι`)っ，万分感谢！！

**Comment by leftstick** [comment]
> 很抱歉，我又打开了这个。希望作者解答，万分感谢！
> 按照官方demo，地图能够显示出来，但是热点并没有出现，并且报了一个错误。
> **### component代码如下：**
> ![image](https://user-images.githubusercontent.com/37288957/60959062-178c1d80-a33a-11e9-82a5-30885eec843d.png)
> ![image](https://user-images.githubusercontent.com/37288957/60959069-1a870e00-a33a-11e9-8a46-6a1c13a78c4a.png)
> 
> ### **html代码如下：**
> ![image](https://user-images.githubusercontent.com/37288957/60958918-d3008200-a339-11e9-893d-f151c1d97009.png)
> 
> ### **浏览器出现错误：**
> ![image](https://user-images.githubusercontent.com/37288957/60958900-c714c000-a339-11e9-813d-8f9725357ec7.png)
> 
> 万分感谢！！！

这个问题，我猜是`heatData`没有初始化就被使用导致的错误，所以你可以在最上面先初始化一下，如：

```typescript
public heatData: HeatmapData = [];
```



===============分割线======================

至于第二个路由切换以后就不显示的问题，我的文档示例里，是可以工作的，所以需要你更多的信息，或者你自己可以对照我的示例源码找差异

![change](https://user-images.githubusercontent.com/1059956/61017296-3be10c00-a3c5-11e9-861f-783d4934e162.gif)

**Comment by LiHuiNeng** [comment]
上午好，很感谢您的回答。我在初始化时按照您的指示给了空的默认值，但仍然提示错误。
![image](https://user-images.githubusercontent.com/37288957/61017615-74cdb080-a3c6-11e9-90bf-099e313cecee.png)
![image](https://user-images.githubusercontent.com/37288957/61017623-7d25eb80-a3c6-11e9-8aa3-2ea191aae05f.png)
![image](https://user-images.githubusercontent.com/37288957/61017630-844cf980-a3c6-11e9-8e92-d90c03aaafc6.png)
############
另外第二个问题，html代码会显示NO_NETWORK
![image](https://user-images.githubusercontent.com/37288957/61017768-f58cac80-a3c6-11e9-81b3-6189bc4afe3c.png)
我可能需要按照示例代码一步步排查了。
最后，这真的是一个非常棒的项目，再次感谢您的回答。

**Comment by LiHuiNeng** [comment]
另外我使用的是angular8，这会造成什么影响吗？

**Comment by LiHuiNeng** [comment]
经过排查，发现是文档上添加热力图的数据不准确导致，按照源代码中的示例添加数据，就能够显示出来。
源代码数据添加方法：
![image](https://user-images.githubusercontent.com/37288957/61018778-8c0e9d00-a3ca-11e9-8d7e-f1b5f41c479e.png)

**Comment by leftstick** [comment]
> 另外我使用的是angular8，这会造成什么影响吗？

理论上不会有什么影响，据说angular2之后的版本都做了“很好的向后兼容”。你研究的很细了，很棒。有兴趣加入维护的话那就更好了。我最近比较忙，参与度不是很高，需要高手助力
